const githubResult = """
{
  "total_count": 170618,
  "incomplete_results": false,
  "items": [
    {
      "login": "daniel",
      "id": 635,
      "node_id": "MDQ6VXNlcjYzNQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/635?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/daniel",
      "html_url": "https://github.com/daniel",
      "followers_url": "https://api.github.com/users/daniel/followers",
      "following_url": "https://api.github.com/users/daniel/following{/other_user}",
      "gists_url": "https://api.github.com/users/daniel/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/daniel/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/daniel/subscriptions",
      "organizations_url": "https://api.github.com/users/daniel/orgs",
      "repos_url": "https://api.github.com/users/daniel/repos",
      "events_url": "https://api.github.com/users/daniel/events{/privacy}",
      "received_events_url": "https://api.github.com/users/daniel/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "dkayiwa",
      "id": 1390773,
      "node_id": "MDQ6VXNlcjEzOTA3NzM=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1390773?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dkayiwa",
      "html_url": "https://github.com/dkayiwa",
      "followers_url": "https://api.github.com/users/dkayiwa/followers",
      "following_url": "https://api.github.com/users/dkayiwa/following{/other_user}",
      "gists_url": "https://api.github.com/users/dkayiwa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dkayiwa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dkayiwa/subscriptions",
      "organizations_url": "https://api.github.com/users/dkayiwa/orgs",
      "repos_url": "https://api.github.com/users/dkayiwa/repos",
      "events_url": "https://api.github.com/users/dkayiwa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dkayiwa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielmiessler",
      "id": 50654,
      "node_id": "MDQ6VXNlcjUwNjU0",
      "avatar_url": "https://avatars.githubusercontent.com/u/50654?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielmiessler",
      "html_url": "https://github.com/danielmiessler",
      "followers_url": "https://api.github.com/users/danielmiessler/followers",
      "following_url": "https://api.github.com/users/danielmiessler/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielmiessler/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielmiessler/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielmiessler/subscriptions",
      "organizations_url": "https://api.github.com/users/danielmiessler/orgs",
      "repos_url": "https://api.github.com/users/danielmiessler/repos",
      "events_url": "https://api.github.com/users/danielmiessler/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielmiessler/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "DanielHe4rt",
      "id": 6912596,
      "node_id": "MDQ6VXNlcjY5MTI1OTY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6912596?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielHe4rt",
      "html_url": "https://github.com/DanielHe4rt",
      "followers_url": "https://api.github.com/users/DanielHe4rt/followers",
      "following_url": "https://api.github.com/users/DanielHe4rt/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielHe4rt/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielHe4rt/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielHe4rt/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielHe4rt/orgs",
      "repos_url": "https://api.github.com/users/DanielHe4rt/repos",
      "events_url": "https://api.github.com/users/DanielHe4rt/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielHe4rt/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "Daniel15",
      "id": 91933,
      "node_id": "MDQ6VXNlcjkxOTMz",
      "avatar_url": "https://avatars.githubusercontent.com/u/91933?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/Daniel15",
      "html_url": "https://github.com/Daniel15",
      "followers_url": "https://api.github.com/users/Daniel15/followers",
      "following_url": "https://api.github.com/users/Daniel15/following{/other_user}",
      "gists_url": "https://api.github.com/users/Daniel15/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/Daniel15/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/Daniel15/subscriptions",
      "organizations_url": "https://api.github.com/users/Daniel15/orgs",
      "repos_url": "https://api.github.com/users/Daniel15/repos",
      "events_url": "https://api.github.com/users/Daniel15/events{/privacy}",
      "received_events_url": "https://api.github.com/users/Daniel15/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielgindi",
      "id": 366926,
      "node_id": "MDQ6VXNlcjM2NjkyNg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/366926?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielgindi",
      "html_url": "https://github.com/danielgindi",
      "followers_url": "https://api.github.com/users/danielgindi/followers",
      "following_url": "https://api.github.com/users/danielgindi/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielgindi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielgindi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielgindi/subscriptions",
      "organizations_url": "https://api.github.com/users/danielgindi/orgs",
      "repos_url": "https://api.github.com/users/danielgindi/repos",
      "events_url": "https://api.github.com/users/danielgindi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielgindi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielkrupinski",
      "id": 34515229,
      "node_id": "MDQ6VXNlcjM0NTE1MjI5",
      "avatar_url": "https://avatars.githubusercontent.com/u/34515229?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielkrupinski",
      "html_url": "https://github.com/danielkrupinski",
      "followers_url": "https://api.github.com/users/danielkrupinski/followers",
      "following_url": "https://api.github.com/users/danielkrupinski/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielkrupinski/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielkrupinski/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielkrupinski/subscriptions",
      "organizations_url": "https://api.github.com/users/danielkrupinski/orgs",
      "repos_url": "https://api.github.com/users/danielkrupinski/repos",
      "events_url": "https://api.github.com/users/danielkrupinski/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielkrupinski/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "DanielRosenwasser",
      "id": 972891,
      "node_id": "MDQ6VXNlcjk3Mjg5MQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/972891?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielRosenwasser",
      "html_url": "https://github.com/DanielRosenwasser",
      "followers_url": "https://api.github.com/users/DanielRosenwasser/followers",
      "following_url": "https://api.github.com/users/DanielRosenwasser/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielRosenwasser/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielRosenwasser/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielRosenwasser/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielRosenwasser/orgs",
      "repos_url": "https://api.github.com/users/DanielRosenwasser/repos",
      "events_url": "https://api.github.com/users/DanielRosenwasser/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielRosenwasser/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielstern",
      "id": 4268152,
      "node_id": "MDQ6VXNlcjQyNjgxNTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/4268152?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielstern",
      "html_url": "https://github.com/danielstern",
      "followers_url": "https://api.github.com/users/danielstern/followers",
      "following_url": "https://api.github.com/users/danielstern/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielstern/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielstern/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielstern/subscriptions",
      "organizations_url": "https://api.github.com/users/danielstern/orgs",
      "repos_url": "https://api.github.com/users/danielstern/repos",
      "events_url": "https://api.github.com/users/danielstern/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielstern/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "DanielPetelin",
      "id": 48854670,
      "node_id": "MDQ6VXNlcjQ4ODU0Njcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/48854670?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielPetelin",
      "html_url": "https://github.com/DanielPetelin",
      "followers_url": "https://api.github.com/users/DanielPetelin/followers",
      "following_url": "https://api.github.com/users/DanielPetelin/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielPetelin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielPetelin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielPetelin/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielPetelin/orgs",
      "repos_url": "https://api.github.com/users/DanielPetelin/repos",
      "events_url": "https://api.github.com/users/DanielPetelin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielPetelin/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "bagder",
      "id": 177011,
      "node_id": "MDQ6VXNlcjE3NzAxMQ==",
      "avatar_url": "https://avatars.githubusercontent.com/u/177011?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/bagder",
      "html_url": "https://github.com/bagder",
      "followers_url": "https://api.github.com/users/bagder/followers",
      "following_url": "https://api.github.com/users/bagder/following{/other_user}",
      "gists_url": "https://api.github.com/users/bagder/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/bagder/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/bagder/subscriptions",
      "organizations_url": "https://api.github.com/users/bagder/orgs",
      "repos_url": "https://api.github.com/users/bagder/repos",
      "events_url": "https://api.github.com/users/bagder/events{/privacy}",
      "received_events_url": "https://api.github.com/users/bagder/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielbachhuber",
      "id": 36432,
      "node_id": "MDQ6VXNlcjM2NDMy",
      "avatar_url": "https://avatars.githubusercontent.com/u/36432?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielbachhuber",
      "html_url": "https://github.com/danielbachhuber",
      "followers_url": "https://api.github.com/users/danielbachhuber/followers",
      "following_url": "https://api.github.com/users/danielbachhuber/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielbachhuber/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielbachhuber/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielbachhuber/subscriptions",
      "organizations_url": "https://api.github.com/users/danielbachhuber/orgs",
      "repos_url": "https://api.github.com/users/danielbachhuber/repos",
      "events_url": "https://api.github.com/users/danielbachhuber/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielbachhuber/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "DanielArturoAlejoAlvarez",
      "id": 18106359,
      "node_id": "MDQ6VXNlcjE4MTA2MzU5",
      "avatar_url": "https://avatars.githubusercontent.com/u/18106359?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielArturoAlejoAlvarez",
      "html_url": "https://github.com/DanielArturoAlejoAlvarez",
      "followers_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/followers",
      "following_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/orgs",
      "repos_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/repos",
      "events_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielArturoAlejoAlvarez/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielmuthama",
      "id": 40577986,
      "node_id": "MDQ6VXNlcjQwNTc3OTg2",
      "avatar_url": "https://avatars.githubusercontent.com/u/40577986?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielmuthama",
      "html_url": "https://github.com/danielmuthama",
      "followers_url": "https://api.github.com/users/danielmuthama/followers",
      "following_url": "https://api.github.com/users/danielmuthama/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielmuthama/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielmuthama/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielmuthama/subscriptions",
      "organizations_url": "https://api.github.com/users/danielmuthama/orgs",
      "repos_url": "https://api.github.com/users/danielmuthama/repos",
      "events_url": "https://api.github.com/users/danielmuthama/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielmuthama/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "DanielTakeshi",
      "id": 5532096,
      "node_id": "MDQ6VXNlcjU1MzIwOTY=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5532096?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielTakeshi",
      "html_url": "https://github.com/DanielTakeshi",
      "followers_url": "https://api.github.com/users/DanielTakeshi/followers",
      "following_url": "https://api.github.com/users/DanielTakeshi/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielTakeshi/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielTakeshi/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielTakeshi/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielTakeshi/orgs",
      "repos_url": "https://api.github.com/users/DanielTakeshi/repos",
      "events_url": "https://api.github.com/users/DanielTakeshi/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielTakeshi/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "lemire",
      "id": 391987,
      "node_id": "MDQ6VXNlcjM5MTk4Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/391987?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/lemire",
      "html_url": "https://github.com/lemire",
      "followers_url": "https://api.github.com/users/lemire/followers",
      "following_url": "https://api.github.com/users/lemire/following{/other_user}",
      "gists_url": "https://api.github.com/users/lemire/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/lemire/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/lemire/subscriptions",
      "organizations_url": "https://api.github.com/users/lemire/orgs",
      "repos_url": "https://api.github.com/users/lemire/repos",
      "events_url": "https://api.github.com/users/lemire/events{/privacy}",
      "received_events_url": "https://api.github.com/users/lemire/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielmarbach",
      "id": 174258,
      "node_id": "MDQ6VXNlcjE3NDI1OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/174258?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielmarbach",
      "html_url": "https://github.com/danielmarbach",
      "followers_url": "https://api.github.com/users/danielmarbach/followers",
      "following_url": "https://api.github.com/users/danielmarbach/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielmarbach/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielmarbach/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielmarbach/subscriptions",
      "organizations_url": "https://api.github.com/users/danielmarbach/orgs",
      "repos_url": "https://api.github.com/users/danielmarbach/repos",
      "events_url": "https://api.github.com/users/danielmarbach/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielmarbach/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielfrg",
      "id": 1580714,
      "node_id": "MDQ6VXNlcjE1ODA3MTQ=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1580714?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielfrg",
      "html_url": "https://github.com/danielfrg",
      "followers_url": "https://api.github.com/users/danielfrg/followers",
      "following_url": "https://api.github.com/users/danielfrg/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielfrg/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielfrg/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielfrg/subscriptions",
      "organizations_url": "https://api.github.com/users/danielfrg/orgs",
      "repos_url": "https://api.github.com/users/danielfrg/repos",
      "events_url": "https://api.github.com/users/danielfrg/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielfrg/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "STRd6",
      "id": 18894,
      "node_id": "MDQ6VXNlcjE4ODk0",
      "avatar_url": "https://avatars.githubusercontent.com/u/18894?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/STRd6",
      "html_url": "https://github.com/STRd6",
      "followers_url": "https://api.github.com/users/STRd6/followers",
      "following_url": "https://api.github.com/users/STRd6/following{/other_user}",
      "gists_url": "https://api.github.com/users/STRd6/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/STRd6/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/STRd6/subscriptions",
      "organizations_url": "https://api.github.com/users/STRd6/orgs",
      "repos_url": "https://api.github.com/users/STRd6/repos",
      "events_url": "https://api.github.com/users/STRd6/events{/privacy}",
      "received_events_url": "https://api.github.com/users/STRd6/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "shiffman",
      "id": 191758,
      "node_id": "MDQ6VXNlcjE5MTc1OA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/191758?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/shiffman",
      "html_url": "https://github.com/shiffman",
      "followers_url": "https://api.github.com/users/shiffman/followers",
      "following_url": "https://api.github.com/users/shiffman/following{/other_user}",
      "gists_url": "https://api.github.com/users/shiffman/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/shiffman/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/shiffman/subscriptions",
      "organizations_url": "https://api.github.com/users/shiffman/orgs",
      "repos_url": "https://api.github.com/users/shiffman/repos",
      "events_url": "https://api.github.com/users/shiffman/events{/privacy}",
      "received_events_url": "https://api.github.com/users/shiffman/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "dhinojosa",
      "id": 410757,
      "node_id": "MDQ6VXNlcjQxMDc1Nw==",
      "avatar_url": "https://avatars.githubusercontent.com/u/410757?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/dhinojosa",
      "html_url": "https://github.com/dhinojosa",
      "followers_url": "https://api.github.com/users/dhinojosa/followers",
      "following_url": "https://api.github.com/users/dhinojosa/following{/other_user}",
      "gists_url": "https://api.github.com/users/dhinojosa/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/dhinojosa/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/dhinojosa/subscriptions",
      "organizations_url": "https://api.github.com/users/dhinojosa/orgs",
      "repos_url": "https://api.github.com/users/dhinojosa/repos",
      "events_url": "https://api.github.com/users/dhinojosa/events{/privacy}",
      "received_events_url": "https://api.github.com/users/dhinojosa/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "toastdriven",
      "id": 2449,
      "node_id": "MDQ6VXNlcjI0NDk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/2449?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/toastdriven",
      "html_url": "https://github.com/toastdriven",
      "followers_url": "https://api.github.com/users/toastdriven/followers",
      "following_url": "https://api.github.com/users/toastdriven/following{/other_user}",
      "gists_url": "https://api.github.com/users/toastdriven/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/toastdriven/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/toastdriven/subscriptions",
      "organizations_url": "https://api.github.com/users/toastdriven/orgs",
      "repos_url": "https://api.github.com/users/toastdriven/repos",
      "events_url": "https://api.github.com/users/toastdriven/events{/privacy}",
      "received_events_url": "https://api.github.com/users/toastdriven/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielcompton",
      "id": 811954,
      "node_id": "MDQ6VXNlcjgxMTk1NA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/811954?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielcompton",
      "html_url": "https://github.com/danielcompton",
      "followers_url": "https://api.github.com/users/danielcompton/followers",
      "following_url": "https://api.github.com/users/danielcompton/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielcompton/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielcompton/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielcompton/subscriptions",
      "organizations_url": "https://api.github.com/users/danielcompton/orgs",
      "repos_url": "https://api.github.com/users/danielcompton/repos",
      "events_url": "https://api.github.com/users/danielcompton/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielcompton/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielsogl",
      "id": 15234844,
      "node_id": "MDQ6VXNlcjE1MjM0ODQ0",
      "avatar_url": "https://avatars.githubusercontent.com/u/15234844?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielsogl",
      "html_url": "https://github.com/danielsogl",
      "followers_url": "https://api.github.com/users/danielsogl/followers",
      "following_url": "https://api.github.com/users/danielsogl/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielsogl/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielsogl/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielsogl/subscriptions",
      "organizations_url": "https://api.github.com/users/danielsogl/orgs",
      "repos_url": "https://api.github.com/users/danielsogl/repos",
      "events_url": "https://api.github.com/users/danielsogl/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielsogl/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielschmitz",
      "id": 1509692,
      "node_id": "MDQ6VXNlcjE1MDk2OTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1509692?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielschmitz",
      "html_url": "https://github.com/danielschmitz",
      "followers_url": "https://api.github.com/users/danielschmitz/followers",
      "following_url": "https://api.github.com/users/danielschmitz/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielschmitz/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielschmitz/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielschmitz/subscriptions",
      "organizations_url": "https://api.github.com/users/danielschmitz/orgs",
      "repos_url": "https://api.github.com/users/danielschmitz/repos",
      "events_url": "https://api.github.com/users/danielschmitz/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielschmitz/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "DanielObara",
      "id": 42970570,
      "node_id": "MDQ6VXNlcjQyOTcwNTcw",
      "avatar_url": "https://avatars.githubusercontent.com/u/42970570?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/DanielObara",
      "html_url": "https://github.com/DanielObara",
      "followers_url": "https://api.github.com/users/DanielObara/followers",
      "following_url": "https://api.github.com/users/DanielObara/following{/other_user}",
      "gists_url": "https://api.github.com/users/DanielObara/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/DanielObara/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/DanielObara/subscriptions",
      "organizations_url": "https://api.github.com/users/DanielObara/orgs",
      "repos_url": "https://api.github.com/users/DanielObara/repos",
      "events_url": "https://api.github.com/users/DanielObara/events{/privacy}",
      "received_events_url": "https://api.github.com/users/DanielObara/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielberkompas",
      "id": 1186992,
      "node_id": "MDQ6VXNlcjExODY5OTI=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1186992?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielberkompas",
      "html_url": "https://github.com/danielberkompas",
      "followers_url": "https://api.github.com/users/danielberkompas/followers",
      "following_url": "https://api.github.com/users/danielberkompas/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielberkompas/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielberkompas/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielberkompas/subscriptions",
      "organizations_url": "https://api.github.com/users/danielberkompas/orgs",
      "repos_url": "https://api.github.com/users/danielberkompas/repos",
      "events_url": "https://api.github.com/users/danielberkompas/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielberkompas/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "huri000",
      "id": 5504255,
      "node_id": "MDQ6VXNlcjU1MDQyNTU=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5504255?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/huri000",
      "html_url": "https://github.com/huri000",
      "followers_url": "https://api.github.com/users/huri000/followers",
      "following_url": "https://api.github.com/users/huri000/following{/other_user}",
      "gists_url": "https://api.github.com/users/huri000/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/huri000/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/huri000/subscriptions",
      "organizations_url": "https://api.github.com/users/huri000/orgs",
      "repos_url": "https://api.github.com/users/huri000/repos",
      "events_url": "https://api.github.com/users/huri000/events{/privacy}",
      "received_events_url": "https://api.github.com/users/huri000/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielgtaylor",
      "id": 106826,
      "node_id": "MDQ6VXNlcjEwNjgyNg==",
      "avatar_url": "https://avatars.githubusercontent.com/u/106826?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielgtaylor",
      "html_url": "https://github.com/danielgtaylor",
      "followers_url": "https://api.github.com/users/danielgtaylor/followers",
      "following_url": "https://api.github.com/users/danielgtaylor/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielgtaylor/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielgtaylor/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielgtaylor/subscriptions",
      "organizations_url": "https://api.github.com/users/danielgtaylor/orgs",
      "repos_url": "https://api.github.com/users/danielgtaylor/repos",
      "events_url": "https://api.github.com/users/danielgtaylor/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielgtaylor/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    },
    {
      "login": "danielroe",
      "id": 28706372,
      "node_id": "MDQ6VXNlcjI4NzA2Mzcy",
      "avatar_url": "https://avatars.githubusercontent.com/u/28706372?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/danielroe",
      "html_url": "https://github.com/danielroe",
      "followers_url": "https://api.github.com/users/danielroe/followers",
      "following_url": "https://api.github.com/users/danielroe/following{/other_user}",
      "gists_url": "https://api.github.com/users/danielroe/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/danielroe/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/danielroe/subscriptions",
      "organizations_url": "https://api.github.com/users/danielroe/orgs",
      "repos_url": "https://api.github.com/users/danielroe/repos",
      "events_url": "https://api.github.com/users/danielroe/events{/privacy}",
      "received_events_url": "https://api.github.com/users/danielroe/received_events",
      "type": "User",
      "site_admin": false,
      "score": 1.0
    }
  ]
}
""";
